# Пользователи
## Создать нового пользователя

POST http://localhost:8080/users/register HTTP/1.1
Content-Type: application/json
  # public userType: UserType;

{
  "email": "torans@overlook3.net",
  "name": "Jack",
  "password": "qwerty123",
  "userType": "Pro"
}

###

## Авторизовать пользователя

POST http://localhost:8080/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook3.net",
  "password": "qwerty123"
}

###
