# Пользователи
## Создать нового пользователя

POST http://localhost:8080/users/register HTTP/1.1
Content-Type: application/json
  # public userType: UserType;

{
  "email": "torans@overlook4.net",
  "name": "Jack",
  "password": "qwerty123",
  "userType": "Pro"
}

###

## Авторизовать пользователя

POST http://localhost:8080/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook4.net",
  "password": "qwerty123"
}

###

# Отправить изображение

POST http://localhost:8080/users/65bffd191c02bb6ef28df3ab/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /Users/yury/Desktop/pokemon_rowlet.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# Проверка состояния пользвателя

GET http://localhost:8080/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vazQubmV0IiwibmFtZSI6IkphY2siLCJpZCI6IjY1ZTZmYTk1NjZjYmFhMjRmMmY1MDE2OSIsImlhdCI6MTcwOTY0NTUwNiwiZXhwIjoxNzA5ODE4MzA2fQ.zU2hzxUlzZXi3n_So8UVdnAG4UjLXrHhO7vYyUsOrk8
###
