# Комментарии

## Создать комметрий
POST http://localhost:8080/comments/65d1f37387e79697ef934acb HTTP/1.1
Content-Type: application/json

{
  "text": "text_test",
  "rentId": "65d1f37387e79697ef934acb",
  "userId": "65d1f37387e79697ef934ac1",
  "raiting": 4000
}

###

## Получить
GET http://localhost:8080/comments/65d1f37387e79697ef934acb HTTP/1.1
Content-Type: application/json
